### ISSUE TITLE
Unauthenticated InputTvRemoteChannel

### ISSUE THREAD

**Issue by queequac** [OpenXbox/xbox-smartglass-csharp#101]
According to the source code, InputTvRemoteChannel can only be used when authenticated

https://github.com/OpenXbox/xbox-smartglass-csharp/blob/40bf43a1ed3f6b0eed85183f7615cc7dd8f3e27e/SmartGlass/SmartGlassClient.cs#L170-L175

Now that @mitchcapper implemented that channel, there is a check for the authenticated session, see 

https://github.com/OpenXbox/xbox-smartglass-csharp/blob/40bf43a1ed3f6b0eed85183f7615cc7dd8f3e27e/SmartGlass/SmartGlassClient.cs#L182

As I mentioned somewhere else, I am only making anonymous calls. And since I was pretty sure that the features I am looking for are not requiring an authentication, I simply removed that if-condition above.
And surprise-surprise: it is working!

Was that tested in the latest version without authentication? What scenarios do actually fail?
Maybe only some requests are bound to authentication? I tried `btn.vol_down` and `btn.vol_up`, both work like a charm. Volume of the TV is changing accordingly.

If it is okay, I'd remove that condition, since I would like to prevent authentication if obviously not necessarily needed.

**Comment by mitchcapper** [comment]
I followed the note that was there about needing auth.  It likely is the setting on the xbox itself that may control it as you can set what connections it accepts.  I have no issue with the gating removed.

**Comment by tuxuser** [comment]
Interesting! Some time ago it did not even open the channel when connection unauthenticated and the callback of waiting for said channel triggered an exception in connection flow.

If that condition is obsolete, feel free to remove it.
