### ISSUE TITLE
Debug WaitForMessage never returning

### ISSUE THREAD

**Issue by tuxuser** [OpenXbox/xbox-smartglass-csharp#22]
Works on dotnet, maybe only NET framework is bugged?

**Comment by joelday** [comment]
https://github.com/OpenXbox/xbox-smartglass-csharp/issues/50 is probably related.

**Comment by tuxuser** [comment]
Dataflow TPL as an alternative to current implementation?

https://docs.microsoft.com/en-US/dotnet/standard/parallel-programming/dataflow-task-parallel-library

**Comment by joelday** [comment]
I haven't used it, so I can't speak to it, but there's also ReactiveX (Reactive Extensions). A general theme for us is unidirectional data flow, so it makes sense. Sometimes I think the code can look a bit opaque/esoteric to folks who haven't used these frameworks, though.

**Comment by tuxuser** [comment]
To me, both patters are new, but DataFlow being a native approach (was included with .NET before, now outsourced into its own NuGet) makes me think it would look more familar / maintainable to the .NET community?

**Comment by joelday** [comment]
Should be fixed by #59
