### ISSUE TITLE
Using the library with .NET Framework 4.7.1

### ISSUE THREAD

**Issue by chefbennyj1** [OpenXbox/xbox-smartglass-csharp#49]
Good day,

I've tried to build the project using dotnet, but it ends in errors and a long list of red in my console.

What I'd really like to do is add these smartglass dlls to console application that monitors my home automation and attaches to Alexa.

Is there any chance of some help getting these libraries working in a .net4.7.1 application?

**Comment by tuxuser** [comment]
Please change the following line in the 3x csproj - SmartGlass.Common, SmartGlass, SmartGlass.Nano:

```
<TargetFramework>netstandard2.0</TargetFramework>
```

to

```
<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
```

Now. build it again - if it still errors, post the log output of your build. Thanks!

**Comment by chefbennyj1** [comment]
Oh boy quite a few exceptions.

But, when I did get it built (with errors) I get a "LoaderType" exception in System.Reflection

**Comment by chefbennyj1** [comment]
This is the error in the stack,

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at SmartGlass.Common.AttributeTypeMapping`2.LazyLoadTypes()
   at SmartGlass.Common.AttributeTypeMapping`2.GetKeyForType(Type type)
   at SmartGlass.Messaging.MessageTypeAttribute.GetMessageTypeForType(Type type)
   at SmartGlass.Messaging.MessageBase`1..ctor()
   at SmartGlass.Messaging.Discovery.PresenceRequestMessage..ctor()
   at SmartGlass.Device.<>c.<DiscoverAsync>b__3_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HomeAI2.XboxOne.TestXbox.<test>d__0.MoveNext() in c:\Users\Benjamin\Dropbox\public\HomeAI2\HomeAI2\XboxOne\TestXbox.cs:line 13

**Comment by tuxuser** [comment]
How are you calling the library? is the console powered on while execution?

**Comment by chefbennyj1** [comment]
``` 
 IEnumerable<SmartGlass.Device> devices = await SmartGlass.Device.DiscoverAsync();
            
foreach (SmartGlass.Device device in devices)
{
    Console.WriteLine(device.Name);
}
        }
```

Thank you for your help.
Yes, the console is on. I thought the code above might automagically poll my network for an xbox device and grab its info. I thought Maybe I have to create an instance of SmartglassClient and make requests through it using the discovery info from the code.

**Comment by chefbennyj1** [comment]
I was able to get the libraries built using dotnet build.

However, there is still a reflection error. Or I'm missing dependant dlls for smart glass.
I've got BouncyCastle libraries installed (even though their nuget version naming seems to be wrong).

What other dlls should I have in the bin folder to make this happen?

Thank you again for your patience sir.

**Comment by tuxuser** [comment]
To be honest, you would be better off with porting your application relying on SmartGlass to .NET Standard 2.0 - instead of trying to port SmartGlass to .NET Framework 4.7.*

We don't plan to maintain .NET Framework 4.7 compatibility.

**Comment by joelday** [comment]
You really should be able to use any .NET Standard library from .NET Framework 4.* along with netcore, etc. because that's kinda the entire point of .NET Standard. I can look into this further, but if indeed it is a problem specific to your project (other .dlls etc.) it would be helpful to get as much detail as I can on that System.Reflection exception.

Thanks!

**Comment by joelday** [comment]
As for BouncyCastle, we are using "Portable.BouncyCastle" (https://github.com/onovotny/bc-csharp) which works on all frameworks. If there's a conflict, I'm guessing you can probably switch to this one entirely.

**Comment by joelday** [comment]
Also, I'm unclear on why you need to build this project. Is there an issue with using the library via the NuGet packages?

**Comment by chefbennyj1** [comment]
Ah wonderful, everything is working now. I really want to thank you both for the help. 
It's time for me to let old version of visual studio go and progress forward.
Now with 2017, and an updated Nuget package manager, everything loads and works as expected.

**Comment by chefbennyj1** [comment]
After connecting to the console with the SmartGlassClient, how would you get a list of App Ids and names, in order to start the apps?

I suspect that  "LaunchTitle" and "LaunchTItleById"  is for both Games and Apps.

**Comment by tuxuser** [comment]
> What is the best way to obtain title Ids?

Start titles on console and keep an eye on *ConsoleStatus* messages that are coming in.

**Comment by chefbennyj1** [comment]
Thank you.  I'll have to create a readout class, cool.

One last question, is it possible to send a volume commands?

**Comment by tuxuser** [comment]
That's not implemented in the CSharp version of the library.

Python has it:
https://github.com/OpenXbox/xbox-smartglass-stump-python/blob/master/xbox/stump/manager.py#L391-L414

Rough workings:
1. You get available, configured Infrared devices (json)
2. You look for the button / device that you want to talk to
3. Send the desired button

Sorry, no plans to integrate that anytime soon.
