### ISSUE TITLE
Client hold frames

### ISSUE THREAD

**Issue by Switcher5** [OpenXbox/xbox-smartglass-csharp#53]
When I starting client, video is good, but every seconds the new frames is holding in queue and I see it with hold. After 1 minut, the hold about 10 sec, after 10 minut, the hold about 2 minut, etc. The memory also was hold. Possible this is issue with ffmpeg client.

**Comment by tuxuser** [comment]
As mentioned in the Discord, sorting and dropping of A/V frames is not properly implemented yet.

**Comment by tuxuser** [comment]
Fixed by #60 (by @grill2010)
