### ISSUE TITLE
Sample Streaming with RGB Codec

### ISSUE THREAD

**Issue by BobbyShoe** [OpenXbox/xbox-smartglass-csharp#56]
Do you have an example using the VideoFormat with Nano streaming using the VideoCodec.RGB value?

Thanks.

**Comment by tuxuser** [comment]
Never seen anything other than H264 being used - can you explain under which condition you encounter that?

**Comment by BobbyShoe** [comment]
I tried to used the xbox-client-ffmpeg project to stream xbox content.  It did work, but there was way too much lag to be useful for my purposes.  When using the Microsoft Xbox App the streaming is near real time, and I was hoping to achieve similar performance.

I wanted to try the RGB video format to eliminate the decoding step to increase performance.  I understand this will increase network traffic, but I am willing to accept increased network traffic for performance gain in rendering.

Also do you know if there is a URL that can be used once streaming begins?  I was also experimenting using VLC or some other viewer to render the streaming, but I could not figure out the UDP URL to provide to the player once the stream started.

Thanks for the help.  By the way the libraries have been very helpful so far.

**Comment by tuxuser** [comment]
- Xbox does not support streaming via RGB nor YUV, its a leftover from the base protocol (Windows 10 IoT client)
- Even changing to another format would not improve the increasing lag

Relevant part in the code that needs improvement is VideoAssembler.cs

**Comment by tuxuser** [comment]
Issue #53 tracks this.
