### ISSUE TITLE
XBox Streaming URL available?

### ISSUE THREAD

**Issue by BobbyShoe** [OpenXbox/xbox-smartglass-csharp#57]
Once a streaming session has begun, do you know if there is an available URL from the Xbox that can be provided to another media streaming client for rendering?  If another client can efficiently play the stream that gets invoked, there is not a real need to write custom logic to handle the stream.

I tried to look in Wire Shark, but did not see a useful URL anywhere to try.

Thanks.

**Comment by tuxuser** [comment]
Hey @BobbyShoe 
No, there is no URL that could be parsed by a third-party application.
The `NANO RDP` protocol is a custom layer on top of RTP, so it needs additional parsing to render / playback.

**Comment by joelday** [comment]
> It might be possible to transform the payload to a standard RTP payload and serve it on a local pipe / socket, to feed into third-party renderer.

This would be quite cool.
