### ISSUE TITLE
How to send Xbox-button gamepad message?

### ISSUE THREAD

**Issue by tylearymf** [OpenXbox/xbox-smartglass-csharp#62]
How to send an Xbox button (ⓧ) message, I tried GamepadButtons.View, but it wasn't.

**Comment by tuxuser** [comment]
Xbox Button is called [GamepadButtons.Nexus](https://github.com/OpenXbox/xbox-smartglass-csharp/blob/master/SmartGlass/Enums/GamepadButtons.cs#L10)

**Comment by tylearymf** [comment]
thanks

**Comment by tylearymf** [comment]
> Xbox Button is called [GamepadButtons.Nexus](https://github.com/OpenXbox/xbox-smartglass-csharp/blob/master/SmartGlass/Enums/GamepadButtons.cs#L10)

thanks
