### ISSUE TITLE
Sending GamepadMessage

### ISSUE THREAD

**Issue by BobbyShoe** [OpenXbox/xbox-smartglass-csharp#63]
Are there any samples sending GamepadMessages to the Xbox using an Xbox One controller?  Or is it known if this functionality works?  The messages do not appear to be getting received by the Xbox.  I did try with the Xbox App with the same controller plugged in and that worked.

I can see what looks like a properly structured GamepadState getting passed into SendGamepadStateAsync, however no events appear to be getting registered with the Xbox.

Thanks.

**Comment by unknownskl** [comment]
Do you clear the button press after the first event?
Otherwise the Xbox will recognize it is being pressed, but never 'unpressed' so it won't trigger the action.

**Comment by BobbyShoe** [comment]
Thanks for the suggestion.  I am seeing the clear event sent over as well.  I am using XInput to retrieve the controller state in a loop.  I also tried with various delays in retrieving state to see if that matter.  I tried no delay, 5 ms, 10ms, and 500 ms.

I am not committed to XInput if there is another option.  Honestly I would have preferred an HID type interface to only have events fire in my application when there are actually events fired from the controller.  However XInput appeared to be suggested over HID from what I read.  I am receiving the events fine in my application from the controller though.  I am only sending changes to the console at least when there are changes in state.

Also just an FYI I am having to remap the Buttons bitmask when I receive it to, as apparently the XInput library gives you a Xbox 360 bitmask instead of an Xbox one bitmask.

**Comment by tylearymf** [comment]
`
client = await SmartGlassClient.ConnectAsync("your xbox ip");
public void SendGamepadState(GamepadState pState)
    {
        Task.Run(() => SendGamepadStateAsync(pState));
    }
    async Task SendGamepadStateAsync(GamepadState pState)
    {
        pState.Timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        await client.InputChannel.SendGamepadStateAsync(pState);

        pState.Buttons = GamepadButtons.Clear;
        pState.Timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        await client.InputChannel.SendGamepadStateAsync(pState);
    }`

try this code.it work in my project

**Comment by tylearymf** [comment]
`client = await SmartGlassClient.ConnectAsync("your xbox ip")
public void SendGamepadState(GamepadState pState)
    {
        Task.Run(() => SendGamepadStateAsync(pState));
    }
    async Task SendGamepadStateAsync(GamepadState pState)
    {
        pState.Timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        await client.InputChannel.SendGamepadStateAsync(pState);
        pState.Buttons = GamepadButtons.Clear;
        pState.Timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        await client.InputChannel.SendGamepadStateAsync(pState);
    }`

try this code.it work in my project

**Comment by tuxuser** [comment]
Keep in mind, SmartGlass InputChannel only works inside dashboard / apps, not games.
For games you need Nano.Input

**Comment by BobbyShoe** [comment]
Thanks for the input all.  Tuxuser got me going on right path.  I needed to use the Nano.Input.

**Comment by GonzalezAtWork** [comment]
Hey guys,

I want to build an android service that grabs the input from a xbox360 controller and send it to an xbox one.

Was trying to use this project to learn/understand, but seems that this only covers the streaming part, and not controllers.

Can any of you point me on the right direction?
