### ISSUE TITLE
Using v1.0.5 Authenticated Connection Fails

### ISSUE THREAD

**Issue by wh010ne** [OpenXbox/xbox-smartglass-csharp#66]
Hey Tux & Joel,
First the update IS more stable. Thnx. Analyzing all the async/awaits and Task.Run and Thread.Starts is horrendous. I had to smoke 2 bowls to make sense of it all, along with deprecated or renamed requirements/variables/etc between the packages. All packages need some refactoring to get on the same level. For example, some packages want XSXT Jwt token and named that, while the parent package is looking for XToken Jwt, and they the same thing but you get exceptions unless manual edit. Along with calculating size of payload. Passes Authentication and parsing of tokens.json, but fail authenticated.Connect(ip, hash, xtoken), always ends in a substring exception about limits and position while calling fragment sendasync(), connects anonymously fine but no authenticated connection due to length/position exception. Note: Under python core and REST it works as should. only under NetStandard2.0/Net v4.7.2, it's in SessionMessageTransport  wait for response.

I can get a annon connection but never authenticated. All the variables are dynamic, xtoken refreshes at startup, authenticate succeeds, connection(ip) succeeds, connection(ip,hash, auth) fails with substring limit/length exception in generate CreateRequestMessage().

Ideas? This kinda related to another issue with connections, but I do get a connection a everything seems to work other than an authenticated session. BTW, what are the gain/losses over authenticated/anonymous connections? with/o using Live functions? What would be the limitations?

P.S. Tux I using the "ey...." token (XToken, XSTSToken), don't get a failed auth or anything just the exception for parsing the token.

**Comment by tuxuser** [comment]
80acd7e **Fix authenticated ConnectRequest assembly**
Give that a try

**Comment by wh010ne** [comment]
Thnx Tux! That seemed to have solved that. No more exception.

Thank you for the informative answer with the differences.
