### ISSUE TITLE
How to use winform c#

### ISSUE THREAD

**Issue by Tranquilty** [OpenXbox/xbox-smartglass-csharp#68]
Hello.
I'm trying to use this in a winform application. How would I go about connecting to the console. I can get it to discover and display console info in a list box.

My aim is to just have a winform app with a load of buttons ect that will just type the text in a message box on the xbox for you insted of typing it.

So if anyone can give me an example of this as well that would be great.

**Comment by wh010ne** [comment]
Try something like this:

        //Async Task for Connection Button - Non-Blocking by running it as Task.Run
        private async Task<SmartGlassClient> Connect(string ip, string hash = null, string xtoken = null)
        {
            try
            {
                client = await SmartGlassClient.ConnectAsync(ip, hash, xtoken);
                if (client != null)
                {
                    if (xtoken != null)
                    {
                        await LogActivity("Connected (auth)");
                    }
                    else
                    {
                        await LogActivity("Connected (anon)");
                    }                    
                }
            }
            catch (SmartGlassException e)
            {
                await LogActivity($"Failed to connect: {e.Message}");
            }
            catch (TimeoutException)
            {
                await LogActivity("Timeout while connecting");
            }

            return client;
        }

and call it like this:

await Task.Run(() => Connect(_ipAddress));

**Comment by wh010ne** [comment]
Refer to Closed Issues #64  for some of my experiences. This may help you.

**Comment by Tranquilty** [comment]
> Refer to Closed Issues #64  for some of my experiences. This may help you. You be may be running into framework issues using winforms. Once you get all the dependencies from Nuget and target the correct framework it all works without issue.

okay. how am  I  able to get the console has, token?

**Comment by wh010ne** [comment]
Implement xbox-smartglass-webapi or roll your own auth. I personally just included the Nuget package for XboxLive from MS and token the token from that. You could also directly interface into the smartglass winmd and has it do it for you but that is going against this project. The idea is to roll your own. For an example to start with:

        private async void Authenticate()
        {
            if (AuthService != null)
            {
                await LogActivity("Authenticating Tokens...");
                bool success = await AuthService.AuthenticateAsync();
                if (!success)
                {
                    await LogActivity("Authentication failed!");
                    if (!AuthService.XToken.Valid)
                    {
                        await LogActivity("\r\nToken Expired, Please Refresh / Reauthenticate!!");
                    }
                }
                else
                {
                    using (FileStream fs = File.Open(TokenFilePath, FileMode.Create))
                    {
                        AuthService.DumpToFile(fs);
                    }
                    _userHash = AuthService.UserInformation.Userhash.ToString();
                    _liveId = AuthService.UserInformation.XboxUserId.ToString();
                    _xToken = AuthService.XToken.Jwt.ToString();
                }
            }
        }

_XToken is what your after. Hopefully this helps you.
