### ISSUE TITLE
New issue with Discovery

### ISSUE THREAD

**Issue by wh010ne** [OpenXbox/xbox-smartglass-csharp#70]
Hi Joel and Tux, have you experienced and issues with Discovery in the last day or two? Mysteriously it all the sudden stopped working. This morning all was working fine, then when I got home and fired it up again, no device is discovered. First I thought it was my app so I stepped through it and didn't see anything wrong. So then I tried the python xbox-discovery and also your guys' SmartGlass.Cli v1.0.5 and they also fail to find a device now. The console is discoverable and I see the packets in wireshark, and I can see it under casting devices in (Netflix, YouTube, etc). So then I tried my other app that uses Microsoft.Xbox.Smartglass.dll and I was able to discover, connect, etc just fine. No network issues, and no recent updates installed. any thoughts?

**Comment by tuxuser** [comment]
Can you attach a wireshark pcap please?

**Comment by wh010ne** [comment]
Attached pcap. I've been stepping through MessageTransport and I can see that it is receiving a message back from the right ip for the console. everything good until 

MessageReceived?.Invoke(this, new MessageReceivedEventArgs<IMessage>(message)); 

So I think it might be in the filtering of the message, since it does deserialize and I see all the Xbox info. 

[discovery.zip](https://github.com/OpenXbox/xbox-smartglass-csharp/files/3280387/discovery.zip)

**Comment by wh010ne** [comment]
I think I may have found the issue. In MessageTransport.cs changed:

_client.Client.Bind(new IPEndPoint(IPAddress.Any, 0));

to

_client.Client.Bind(new IPEndPoint(IPAddress.Parse(GetLocalIpAddress()), 0));

and it came back to life. Come to find out that Virtual NICs from VMWare/VirtualBox can interfere with what address your binding to. So rather than disabling those NICs I wrote a little method to get the 'real' IP address filtering out the interfaces no needed. This works for me, unless you've got another approach.
