### ISSUE TITLE
Why GPLv3?

### ISSUE THREAD

**Issue by queequac** [OpenXbox/xbox-smartglass-csharp#77]
Just wanted to know why you changed the license from MIT to GPL v3 on November 11th 2018?
Maybe you can share your thoughts on this? 

GPLv3 definitly limits the potential usage of the library (aside from hobby activities), since this kind of license is very restrictive.

Personally I have been considering to use that library for an upcoming app... but unfortunately I would have to use quite old source code as a starting point that was still under MIT. Not sure if it is really worth the effort to do so. But disclosing my whole app's source is definitly also no option for me.

**Comment by queequac** [comment]
Since I do only need small portions of the overall functionality anyway, I will most likely write my own implementation based on the protocol description.

GPLv3 is incompatible with most of the permissive licenses (e.g. Apache 2.0), so I'd not be able to use it along with other libraries I depend on.

BTW, BouncyCastle is licensed under MIT, which I would also consider to be incompatible with GPLv3. That alone would be reason enough for you to consider re-licensing under MIT.

**Comment by tuxuser** [comment]
You are right, GPL v3 is way too restrictive.
The license was changed to MIT.

**Comment by joelday** [comment]
https://www.youtube.com/watch?v=I25UeVXrEHQ
