### ISSUE TITLE
generating XSTS and uhs

### ISSUE THREAD

**Issue by theRemoter** [OpenXbox/xbox-smartglass-csharp#78]
Userhash: Xbox Live Userhash (uhs)
Auth Token: Xbox Live Auth token (XSTS)

how can those be generated?
If I want to send a connect request, I must fill them up, but there is no mention of how to get those two in the documentation.

**Comment by tuxuser** [comment]
You want to use OpenXbox.XboxWebApi (nuget)

https://github.com/OpenXbox/xbox-webapi-csharp
https://www.nuget.org/packages/OpenXbox.XboxWebApi
