### ISSUE TITLE
Configurable local endpoint for broadcast

### ISSUE THREAD

**Issue by queequac** [OpenXbox/xbox-smartglass-csharp#87]
I ran into exactly the same issue like #70 did in the past.

One of my machines has several virtual adapters and most of them have automatic priority for the interface metric. Unfortunately Windows gives one of these adapters a higher priority and it seems that netcore is then simply using the first IPv4 one that should do the job (but obviously does not).

So I do also look through the network interfaces and select the first one that is IPv4 **and** has a gateway. So I am able to pass in my real primary IP address instead of IPAddress.ANY and it works.

Of course IPAddress.ANY is a valid default and I do not think you'd like to replace it in the way described above. But would it be an option to extend the interface in a way that allows providing a custom IP address for the local endpoint? Then the default could remain as-is, but others (like me or the one from the issue mentioned above 😉) could set an alternative without the need of modifying the smartglass library itself. We could stick to the regular NuGet package instead.

I would have to check whether this applies for `MessageTransport.cs` only, or if `NanoRdpTransport.cs` should be treated likewise.

**Comment by tuxuser** [comment]
Can you verify this suits your needs? https://github.com/OpenXbox/xbox-smartglass-csharp/tree/fix/implement_socket_bindaddr

**Comment by queequac** [comment]
Unfortunately not completely, since discovery is done via Device.DiscoverAsync. Might also be needed for PingAsync and PowerOnAsync,... maybe more somewhere else?

I am unsure about always adding more optional arguments to several (public) constructors and methods.
Maybe this could also be some central static setting (e.g. in the Device class or completely separated) which defaults to IPAddress.Any and could be overwritten when needed. Would result in cleaner API and the method transport implementation could simply take the value from the central configuration.

**Comment by tuxuser** [comment]
That sounds like a very good idea idea!
